---
title: "Bayesian diagnostics"
author: "Alejandro Castellanos"
output: html_notebook
---

# Load libraries
```{r}
library(tidyverse)
library(broom)
library(coda)
```
```{r}
growth <- read_rds("growth.rds")

```

```{r}
taxa <-  c('B_caccae',
        'B_cellulosilyticus_WH2',
        'B_ovatus',
        'B_thetaiotaomicron',
        'B_uniformis',
        'B_vulgatus',
        'C_aerofaciens',
        'C_scindens',
        'C_spiroforme',
        'D_longicatena',
        'P_distasonis',
        'R_obeum')
```

```{r}
sopa <- matrix(NA, nrow = 24000, ncol = 12)
for (i in 1:12) {
  sopa[,i] <- growth[1, 1:24000, i]
}
colnames(sopa) <- taxa
sopa
```


```{r}
lima <- cbind(growth[2, 1:24000, 1],  growth[2, 1:24000, 2], growth[2, 1:24000, 3], growth[2, 1:24000, 4], growth[2, 1:24000, 5], growth[2, 1:24000, 6], growth[2, 1:24000, 7], growth[2, 1:24000, 8], growth[2, 1:24000, 9], growth[2, 1:24000, 10], growth[2, 1:24000, 11], growth[2, 1:24000, 12])
colnames(lima) <- taxa
```


```{r}
# yuca <- mcmc(data = data.frame(growth[1, 1:24000, 1]))

yuca <- mcmc(data = sopa)

pera <- mcmc(data = lima)

chipi <- mcmc.list(yuca, pera)
```



```{r}
gelman.plot(chipi, autoburnin = FALSE)
```

```{r}
gelman.diag(chipi)
```

```{r}
hopo <- heidel.diag(yuca)
hopo
```



```{r}
geweke.diag(yuca)
```